version: '3.9'

services:
  blockchain:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build
    ports:
      - '9000:9000'
    volumes:
      - ./app:/app
    tty: true
    stdin_open: true